/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_HELLOWORLD_T_H
#define EDGER8R_HELLOWORLD_T_H

#include <openenclave/enclave.h>
#include "helloworld_args.h"

OE_EXTERNC_BEGIN

/* List of ecalls */

void enclave_new_tx(void);

/* List of ocalls */

oe_result_t host_return_tx(
        );

OE_EXTERNC_END

#endif // EDGER8R_HELLOWORLD_T_H
